// Backwards compatibility only. CLI 1.11.0–1.13.0 stamped skill packs without
// a contentHash. This table holds each pack's hash as those releases installed
// it, so auto-refresh can tell their unedited packs from edited ones.
// Needs no maintenance: every later CLI records the contentHash in the stamp
// at install time. Generated by scripts/legacy-skill-hashes.mjs.
export const LEGACY_SKILL_HASHES: Record<string, Record<string, string>> = {
  "1.11.0": {
    "cc-workflow": "9fa4a5b8e3983b64a3213e4b78db6f3008120d1131266e25896a20ba07e281b3",
    "cc-workflow-build": "5ebcfb75c61a40db84d5c1ed24c3878f1cbaff05684c1294806d0ebaf76823f8",
    "cc-workflow-setup": "85af3e1bc73b5af22b1ce409b2bc0845a6ef5b08e269203ef398764275ff0e46",
    "cc-workflow-test": "ace194d0f93541a75f06336d1f68a61b859529617ec2b7d418716d1024c3126d",
    "cloudcruise": "91b45cada48f76a7afd3f00393373be61d38845422efdec92e32f69303b614c6",
    "cloudcruise-workflow-dsl": "0211c80e767d7e5670c11aa3cf9b1b9d4259a6bb73ea3d1b343f4d35c97bbeda"
  },
  "1.11.1": {
    "cc-workflow": "9fa4a5b8e3983b64a3213e4b78db6f3008120d1131266e25896a20ba07e281b3",
    "cc-workflow-build": "5ebcfb75c61a40db84d5c1ed24c3878f1cbaff05684c1294806d0ebaf76823f8",
    "cc-workflow-setup": "85af3e1bc73b5af22b1ce409b2bc0845a6ef5b08e269203ef398764275ff0e46",
    "cc-workflow-test": "ace194d0f93541a75f06336d1f68a61b859529617ec2b7d418716d1024c3126d",
    "cloudcruise": "a60f28ed46df7722f35512e5bcc4b7b30364d43549df09d4e258f79cb6a54af1",
    "cloudcruise-workflow-dsl": "0211c80e767d7e5670c11aa3cf9b1b9d4259a6bb73ea3d1b343f4d35c97bbeda"
  },
  "1.11.2": {
    "cc-workflow": "266e003c9fde46947aca04b0fa665d54bde13287f78dd8299ffd07ed1a38e3b0",
    "cc-workflow-build": "2b60bd49d454c02485db46ce49b5c23bb9edd7e9dabadcb4a52d0aa7d7c27cc1",
    "cc-workflow-setup": "ca0319370bf7cf4fa99501e57ebff276476121e464733021aaf007161264a584",
    "cc-workflow-test": "351a34a59a2fb47987caf14ac2e1443216956df97dc016a5ff7b11e3209c4422",
    "cloudcruise": "a60f28ed46df7722f35512e5bcc4b7b30364d43549df09d4e258f79cb6a54af1",
    "cloudcruise-workflow-dsl": "0211c80e767d7e5670c11aa3cf9b1b9d4259a6bb73ea3d1b343f4d35c97bbeda"
  },
  "1.11.3": {
    "cc-workflow": "266e003c9fde46947aca04b0fa665d54bde13287f78dd8299ffd07ed1a38e3b0",
    "cc-workflow-build": "2b60bd49d454c02485db46ce49b5c23bb9edd7e9dabadcb4a52d0aa7d7c27cc1",
    "cc-workflow-setup": "ca0319370bf7cf4fa99501e57ebff276476121e464733021aaf007161264a584",
    "cc-workflow-test": "351a34a59a2fb47987caf14ac2e1443216956df97dc016a5ff7b11e3209c4422",
    "cloudcruise": "234023bde493af17de95b96b355cc71d592867060c30ea689dfd460bf098e8a6",
    "cloudcruise-workflow-dsl": "0211c80e767d7e5670c11aa3cf9b1b9d4259a6bb73ea3d1b343f4d35c97bbeda"
  },
  "1.11.4": {
    "cc-workflow": "3372e88dd1d4fae1dfecc6ecf6a1577fd49935a650698249115a3c5e8ac65609",
    "cc-workflow-build": "48405b988eba8174705bc2f69b6aeed5a98f10508b1e2010748a021bcdfd493a",
    "cc-workflow-setup": "ef69dfbcb427537dc8858652af604ac04ae728ae5819a15f70cf71b44dd11da0",
    "cc-workflow-test": "5d3c1be84f9d78ca1cad218aa1a6c868307d2991e1fe7020027fcb0cdb8213df",
    "cloudcruise": "234023bde493af17de95b96b355cc71d592867060c30ea689dfd460bf098e8a6",
    "cloudcruise-workflow-dsl": "0211c80e767d7e5670c11aa3cf9b1b9d4259a6bb73ea3d1b343f4d35c97bbeda"
  },
  "1.11.5": {
    "cc-workflow": "3372e88dd1d4fae1dfecc6ecf6a1577fd49935a650698249115a3c5e8ac65609",
    "cc-workflow-build": "f18057c8ca85c950bde04be54199f88d60c8b584b7f51f324521303fac601a7a",
    "cc-workflow-setup": "58ae5e99eecc766cb3a64c0d4ea7287dd122b99d5f23698201b8f40215818b2f",
    "cc-workflow-test": "61ac243adb61641836406a6a1c8e826fc65ba2d92021cdf843d6ea5ed0721280",
    "cloudcruise": "234023bde493af17de95b96b355cc71d592867060c30ea689dfd460bf098e8a6",
    "cloudcruise-workflow-dsl": "0211c80e767d7e5670c11aa3cf9b1b9d4259a6bb73ea3d1b343f4d35c97bbeda"
  },
  "1.11.6": {
    "cc-workflow": "3372e88dd1d4fae1dfecc6ecf6a1577fd49935a650698249115a3c5e8ac65609",
    "cc-workflow-build": "f18057c8ca85c950bde04be54199f88d60c8b584b7f51f324521303fac601a7a",
    "cc-workflow-setup": "58ae5e99eecc766cb3a64c0d4ea7287dd122b99d5f23698201b8f40215818b2f",
    "cc-workflow-test": "61ac243adb61641836406a6a1c8e826fc65ba2d92021cdf843d6ea5ed0721280",
    "cloudcruise": "b97df2e5f6e7d8030b7c16d0a7a007f2cd895ba82646cc4530150477a3c104a9",
    "cloudcruise-workflow-dsl": "0211c80e767d7e5670c11aa3cf9b1b9d4259a6bb73ea3d1b343f4d35c97bbeda"
  },
  "1.11.7": {
    "cc-workflow": "3372e88dd1d4fae1dfecc6ecf6a1577fd49935a650698249115a3c5e8ac65609",
    "cc-workflow-build": "f18057c8ca85c950bde04be54199f88d60c8b584b7f51f324521303fac601a7a",
    "cc-workflow-setup": "58ae5e99eecc766cb3a64c0d4ea7287dd122b99d5f23698201b8f40215818b2f",
    "cc-workflow-test": "61ac243adb61641836406a6a1c8e826fc65ba2d92021cdf843d6ea5ed0721280",
    "cloudcruise": "b97df2e5f6e7d8030b7c16d0a7a007f2cd895ba82646cc4530150477a3c104a9",
    "cloudcruise-workflow-dsl": "bc872df16c84456a19b4b9e81dbf8045d3d1cda9ce302e8624047e33cc86070c"
  },
  "1.12.0": {
    "cc-workflow": "3372e88dd1d4fae1dfecc6ecf6a1577fd49935a650698249115a3c5e8ac65609",
    "cc-workflow-build": "f18057c8ca85c950bde04be54199f88d60c8b584b7f51f324521303fac601a7a",
    "cc-workflow-setup": "58ae5e99eecc766cb3a64c0d4ea7287dd122b99d5f23698201b8f40215818b2f",
    "cc-workflow-test": "61ac243adb61641836406a6a1c8e826fc65ba2d92021cdf843d6ea5ed0721280",
    "cloudcruise": "8f7c2d6187ab3b360dde579c16217446edb9d9e849a34c72ec40c3eb74c988b4",
    "cloudcruise-workflow-dsl": "481f07be5a9eec3d5e99437a40ade96efbe1a612c9e5692cf892d2bedde04e81"
  },
  "1.12.1": {
    "cc-workflow": "398d446d7f74d5075c207a66c883feeeb8f6c4053e68977a334edcadb7c79495",
    "cc-workflow-build": "8d8b2e81b78b8f1a9c56b5ddecf3e5a20ff013da3307a439550f37ea68def273",
    "cc-workflow-setup": "1c7e72ca8500d50ed1c4bd11464a2dfe112ddb89cf3186abcaee24a67c2f573d",
    "cc-workflow-test": "12f53ad847afba3b65b7131765a85279b21354e87bd17b3537d638f366080ce7",
    "cloudcruise": "8f7c2d6187ab3b360dde579c16217446edb9d9e849a34c72ec40c3eb74c988b4",
    "cloudcruise-workflow-dsl": "005f0b785c1d9b72da6cdd006126169c279c924f3896573bb85f4dd2e6add90b"
  },
  "1.13.0": {
    "cc-workflow": "4f7369e0b9dfefe9949305907f7db46c0481be4e37a94aa2aa20bd0f709e662f",
    "cc-workflow-build": "d93835a0a99f9ff645a5ff1145220001b161a73ee7d4f3f208f45f74be2611f0",
    "cc-workflow-setup": "9c412744cf668fc94ff4e1c17905175abfe7cbbaa613607f1bfd3982e0450cfa",
    "cc-workflow-test": "e0e4abee8ab1ad5fddbba09a78d83d1a14b6dc7e95a44590b739a9498c7d391c",
    "cloudcruise": "1d7d8222667bc714e3cfda53b0d6daa19bd81819dff20f378b66d4e9750a3b7f",
    "cloudcruise-workflow-dsl": "3e0a8b00f7cd42ebea86cf99b58ab009edb9a1a4efb58a886be7867191a23e7f"
  }
}
